apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8081"
  TRIP_SERVICE_URL: "http://trip-service:8083"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  RABBITMQ_EXCHANGE: "ride-sharing.events"